name: pyg_ms
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - asttokens=3.0.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_9
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2025.1.31=py39h06a4308_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py39h06a4308_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.8=3
  - curl=7.88.1=hdc1c0ab_0
  - debugpy=1.8.11=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - idna=3.7=py39h06a4308_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py39h06a4308_1
  - ipython=8.15.0=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h6a678d5_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcurl=7.88.1=hdc1c0ab_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libsanitizer=14.2.0=hed042b8_2
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.16=h5eee18b_0
  - pango=1.50.14=hd33c08f_0
  - parso=0.8.4=py39h06a4308_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39h2320bf1_1
  - pip=25.0=py39h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.7=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python_abi=3.9=2_cp39
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.2.0=py39h6a678d5_0
  - r-base=4.2.2=ha7d60f8_3
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_1
  - rpy2=3.5.9=py39r42h389d5f1_0
  - sed=4.8=he412f7d_0
  - setuptools=75.8.0=py39h06a4308_0
  - simplegeneric=0.8.1=pyhd8ed1ab_2
  - six=1.17.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tktable=2.10=h8bc8fbc_6
  - torchaudio=0.13.1=py39_cu117
  - torchvision=0.14.1=py39_cu117
  - tornado=6.4.2=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - tzlocal=5.3=py39hf3d152e_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.10.9
      - array-api-compat==1.11.2
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - botocore==1.31.17
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dask==2024.8.0
      - dask-expr==1.1.10
      - dask-image==2024.5.3
      - datashader==0.17.0
      - distributed==2024.8.0
      - docrep==0.3.2
      - exceptiongroup==1.2.2
      - fasteners==0.19
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2023.6.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - h5py==3.13.0
      - igraph==0.11.8
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-scalebar==0.9.0
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numcodecs==0.12.1
      - numpy==1.26.4
      - ome-zarr==0.10.2
      - omnipath==1.0.9
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.1
      - param==2.2.0
      - partd==1.4.2
      - patsy==1.0.1
      - pims==0.7
      - pooch==1.8.2
      - propcache==0.3.1
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pyct==0.5.0
      - pyg-lib==0.4.0+pt113cu117
      - pynndescent==0.5.13
      - pyogrio==0.10.0
      - pyparsing==3.2.3
      - pyproj==3.6.1
      - pyyaml==6.0.2
      - rich==14.0.0
      - s3fs==2023.6.0
      - scanpy==1.9.8
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - session-info==1.0.1
      - shapely==2.0.7
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.1.0
      - spatialdata==0.2.5.post0
      - squidpy==1.6.1
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - tblib==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - toolz==1.0.0
      - torch-cluster==1.6.1+pt113cu117
      - torch-geometric==2.5.3
      - torch-scatter==2.1.1+pt113cu117
      - torch-sparse==0.6.17+pt113cu117
      - torch-spline-conv==1.2.2+pt113cu117
      - tqdm==4.67.1
      - typeguard==4.4.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==1.26.20
      - validators==0.34.0
      - wrapt==1.17.2
      - xarray==2024.7.0
      - xarray-dataclasses==1.9.1
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.20.0
      - zarr==2.18.2
      - zict==3.0.0
prefix: /home/llx/software/miniconda3/envs/pyg_ms
